/**
 * FUSIONONE — PRODUCTION SCHEMA RECONCILIATION: extract the live definitions of
 * the two functions replaced by migration 0019 (create_trade_in_purchase_bill,
 * cancel_sale) from BOTH projects, STRICTLY READ-ONLY, and:
 *
 *   1. write the PRODUCTION pre-migration definitions + their grant statements
 *      to /home/z/prodreconc/rollback-0019.sql — the surgical rollback script
 *      (restores the exact pre-state bodies if ever required);
 *   2. write the TEST (reference) definitions to
 *      /home/z/prodreconc/reference-0019-test.sql;
 *   3. print a compact comparison of the three sources:
 *      TEST live body vs the repository's 0019 file vs PRODUCTION live body.
 *
 * Usage:
 *   FUSIONONE_DB_URL='postgresql://postgres.<ref>:<pw>@<pooler>:5432/postgres' \
 *     bun run prodreconc-fndefs.ts
 */
import postgres from 'postgres'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const PROD_REF = 'jzdnesudczqksghosmmx'
const TEST_REF = 'egdrnhtmclvhsfjvhyam'

function loadEnv(): Record<string, string> {
  const raw = readFileSync(join(HERE, '.env'), 'utf8')
  return Object.fromEntries(
    raw.split('\n').filter((l: string) => l.includes('=') && !l.startsWith('#')).map((l: string) => {
      const i = l.indexOf('=')
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()]
    }),
  )
}
const env = loadEnv()
const PROD_URL = process.env.FUSIONONE_DB_URL
const TEST_URL = env.TEST_SUPABASE_DB_URL
if (!PROD_URL?.includes(PROD_REF)) throw new Error('SAFETY ABORT: FUSIONONE_DB_URL is not the production project.')
if (!TEST_URL?.includes(TEST_REF)) throw new Error('SAFETY ABORT: .env TEST URL is not the TEST project.')

const SIGS = ['create_trade_in_purchase_bill(uuid, uuid)', 'cancel_sale(uuid)']

async function getDefs(url: string) {
  const sql = postgres(url, { ssl: { rejectUnauthorized: false }, max: 1, prepare: false, idle_timeout: 5 })
  const defs: Record<string, string> = {}
  const grants: Record<string, string[]> = {}
  for (const fn of ['create_trade_in_purchase_bill', 'cancel_sale']) {
    const r = await sql`
      select pg_get_functiondef(p.oid) as def from pg_proc p
       where p.pronamespace='public'::regnamespace and p.proname=${fn}`
    defs[fn] = r[0].def
    const sig = SIGS.find((s) => s.startsWith(fn + '('))!
    const a = await sql`
      select has_function_privilege('public', ${sig}, 'EXECUTE') as pub,
             has_function_privilege('authenticated', ${sig}, 'EXECUTE') as auth,
             has_function_privilege('service_role', ${sig}, 'EXECUTE') as svc`
    grants[fn] = [`pub=${a[0].pub}`, `authenticated=${a[0].auth}`, `service_role=${a[0].svc}`]
  }
  await sql.end()
  return { defs, grants }
}

const prod = await getDefs(PROD_URL)
const test = await getDefs(TEST_URL)

// ── Rollback script: exact production pre-state ──────────────────────────────
const rollback: string[] = [
  '-- FUSIONONE — surgical rollback for migration 0019 on production',
  '-- (jzdnesudczqksghosmmx). Restores the EXACT pre-0019 function bodies',
  '-- captured read-only immediately before the migration was applied.',
  '-- Generated by database/tools/prodreconc-fndefs.ts — DO NOT EDIT BY HAND.',
  '',
]
for (const fn of ['create_trade_in_purchase_bill', 'cancel_sale']) {
  rollback.push(prod.defs[fn].trim() + ';', '')
  rollback.push(`REVOKE EXECUTE ON FUNCTION public.${SIGS.find((s) => s.startsWith(fn + '('))} FROM PUBLIC, anon;`)
  rollback.push(`GRANT EXECUTE ON FUNCTION public.${SIGS.find((s) => s.startsWith(fn + '('))} TO authenticated, service_role;`, '')
}
rollback.push("DELETE FROM public.schema_migrations WHERE version = '0019_recovery_and_reversal_date_invariant.sql';")
writeFileSync('/home/z/prodreconc/rollback-0019.sql', rollback.join('\n'))

// ── Reference definitions from TEST ──────────────────────────────────────────
writeFileSync('/home/z/prodreconc/reference-0019-test.sql',
  '-- FUSION ONE — TEST live definitions of the two 0019-replaced functions\n' +
  '-- (the authoritative target state, captured read-only).\n\n' +
  Object.values(test.defs).map((d) => d.trim() + ';').join('\n\n') + '\n')

// ── Comparison: TEST live vs 0019 file vs PROD live ──────────────────────────
const file = readFileSync(join(HERE, '..', 'migrations', '0019_recovery_and_reversal_date_invariant.sql'), 'utf8')
const norm = (s: string) => s.replace(/\s+/g, ' ').trim()

const CLAMP_MARK = 'GREATEST(fy.start_date, LEAST(current_date'

for (const fn of ['create_trade_in_purchase_bill', 'cancel_sale']) {
  const t = norm(test.defs[fn])
  const p = norm(prod.defs[fn])
  const fileBody = normSqlBody(file, fn)
  console.log('')
  console.log('=== ' + fn + ' ===')
  console.log('  TEST grants : ' + test.grants[fn].join(' '))
  console.log('  PROD grants : ' + prod.grants[fn].join(' '))
  console.log('  TEST body contains clamp   : ' + t.includes(CLAMP_MARK))
  console.log('  PROD body contains clamp   : ' + p.includes(CLAMP_MARK))
  const same = fileBody === t
  console.log('  TEST == 0019 file (norm)   : ' + (same ? 'YES' : 'NO (see diff below)'))
  if (!same) {
    console.log('  -- file body --')
    console.log(fileBody.slice(0, 400))
    console.log('  -- test body --')
    console.log(t.slice(0, 400))
  }
  console.log('  PROD differs from TEST     : ' + (p !== t ? 'YES (expected — 0019 pending)' : 'NO'))
}

function normSqlBody(sqlFile: string, fn: string): string {
  // extract the CREATE OR REPLACE FUNCTION block for fn from the 0019 file
  const start = sqlFile.indexOf(`CREATE OR REPLACE FUNCTION public.${fn}(`)
  if (start < 0) return ''
  const end = sqlFile.indexOf('$$;', start)
  return norm(sqlFile.slice(start, end + 3))
}

console.log('\n✓ rollback script : /home/z/prodreconc/rollback-0019.sql')
console.log('✓ TEST reference  : /home/z/prodreconc/reference-0019-test.sql')
